---
- name: Lghthouse | install dependencies
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Lighthouse | Create a directory lighthouse
  ansible.builtin.file:
    path: "{{ lighthouse_location_dir }}"
    state: directory
    mode: 0755
  become: true
- name: Lighthouse | Copy from git
  become: true
  git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location_dir }}"
    recursive: true
- name: Lighthouse | Create lighthouse config
  become: true
  template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: reload-nginx